# Generated by Django 5.2.2 on 2025-06-10 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_choice_is_correct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionuser',
            unique_together={('question', 'user')},
        ),
    ]
