# Generated by Django 5.2.2 on 2025-06-10 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_question_choices_choice_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='users_passed',
            field=models.ManyToManyField(related_name='tests_passed', to=settings.AUTH_USER_MODEL),
        ),
    ]
