# Generated by Django 5.2.2 on 2025-06-10 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_users_passed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users_passed',
            field=models.ManyToManyField(blank=True, related_name='tests_passed', to=settings.AUTH_USER_MODEL),
        ),
    ]
