# Generated by Django 5.2.2 on 2025-06-09 16:15

import authsys.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authsys.models.CustomManager()),
            ],
        ),
    ]
